web/config/routes.rb
Mdash::Application.routes.draw do
  post 'munin/update' => 'hosts#munin_update'
  get 'search' => 'search#query'
  resources :hosts

  root :to => 'hosts#index'

end

web/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :muplugins
end

web/app/models/domain.rb
class Domain < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  has_many :hosts, :dependent => :destroy

  def self.sorted_with_hosts
    domains = Array.new
    Domain.order("name ASC").each do |d|
      domains << d if d.hosts.count > 0
    end
    domains
  end

  def self.select_update(domain_name)
    unless d= Domain.find_by_name(domain_name)
      d = Domain.new
      d.name = domain_name
      d.save
    end
    d
  end
end

web/app/models/host.rb
class Host < ActiveRecord::Base
  belongs_to :domain
  has_many :muplugins, :dependent => :destroy
  has_many :categories, :through => :muplugins

  validates :name, :presence => true, :uniqueness => true


  def get_plugins_by_category_id(category_id)
    muplugins.where("category_id = ?", category_id).order("plg_title ASC")
  end

  def get_categories
    categories.group("name").order("name ASC")
  end
end

web/app/models/muplugin.rb
class Muplugin < ActiveRecord::Base
  belongs_to :category
  belongs_to :host

  def filename
    File.join('plugin_data', host.name + '__' + plg_name + '.muconfig')
  end
  
  def graph_field_filename(field)
    "servers." + host.name.split(".").reverse.join(".") + "." + graphite_name.downcase + "." + field.downcase
  end
  
  def graph(time_start = "-30h", time_end = "now")
    munin_plg = Munin::Plugin.new(plg_name, IO.readlines(filename))
    graph_height = Configuration.graph_height
    # Add some height if more field are available
    if munin_plg.fields.count() > 5
      graph_height = graph_height.to_i + (munin_plg.fields.count * 3)
    end
    ggraph = GraphiteGraph.new(:none)
    ggraph.title plg_title
    ggraph.vtitle munin_plg.vlabel
    ggraph.from time_start.to_s
    ggraph.until time_end.to_s
    ggraph.width Configuration.graph_width
    ggraph.height graph_height
    ggraph.hide_legend false
    ggraph.ymax munin_plg.ymax if munin_plg.ymax
    ggraph.ymin munin_plg.ymin if munin_plg.ymin
    ggraph.yunit_system munin_plg.yunit_system if munin_plg.yunit_system
    # Color Stuff
    ggraph.major_grid_line_color Configuration.graph_major_grid_line_color
    ggraph.minor_grid_line_color Configuration.graph_minor_grid_line_color
    ggraph.background_color Configuration.graph_background_color
    ggraph.foreground_color Configuration.graph_foreground_color
    # Custom format for daily graph
    if time_start.to_s == Configuration.graph_time_day
      ggraph.xformat '%a %H:%M'
    end
    ggraph.fontsize Configuration.graph_fontsize
    graph_id = 0
    munin_plg.fields.each do |k|
      color = Configuration.graph_single_color
      if munin_plg.fields.count > 1
        color = get_color(graph_id)
      end
      foptions = munin_plg.get_field(k)
      ggraph.field ":#{k}", :data => graph_field_filename(k),
        :alias => foptions[:desc],
        :derivative => foptions[:derivative],
        :scale_to_seconds => foptions[:scale_to_seconds],
        :scale => foptions[:scale],
        :color => color
      graph_id += 1
    end
    url = Configuration.graphite_url + ggraph.url

    return url
  end

  def get_color(id)
    if id > Configuration.graph_colors.split(/ /).count
      id = id - (Configuration.graph_colors.split(/ /).count - 1 )
    end
    Configuration.graph_colors.split(/ /)[id]
  end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

web/app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  protect_from_forgery :except => :munin_update
  def index
    @domains = Domain.sorted_with_hosts
    @hosts = Host.all
  end

  def munin_update
    json = JSON.parse(params[:json])
    json.keys.each do |host|
      hostname, domainname = host.to_s.split(/\./, 2)
      @domain = Domain.select_update(domainname)
      if !@host = @domain.hosts.find_by_name(host)
        @host = @domain.hosts.new
        @host.name = host
        @host.save
      end
      json[host].keys.each do |plugin|
        munin_plugin = Munin::Plugin.new(plugin, json[host][plugin]["config"])
        unless @category = Category.find_by_name(munin_plugin.category)
          @category = Category.new
          @category.name = munin_plugin.category
          @category.save
        end

        unless @muplugin = @host.muplugins.find_by_plg_name(plugin)
          @muplugin = @host.muplugins.new
          @muplugin.plg_name = plugin
        end
        @muplugin.category_id   = @category.id
        @muplugin.graphite_name = json[host][plugin]["name_clean"]
        @muplugin.plg_title     = munin_plugin.plg_title
        @muplugin.plg_info      = munin_plugin.plg_info
        @muplugin.save
        File.open(@muplugin.filename, 'w') do |f|
          f.puts json[host][plugin]["config"]
        end
        

      ## FIXME: Delete Old plugins from database
      end
    end
  end

  def show
    @host = Host.find(params[:id])
  end
end

web/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def query
    @hosts = Host.where('name LIKE ?', '%' + params[:search_box] + '%')
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/search_helper.rb
module SearchHelper
end

web/app/views/hosts/index.html.erb
<h1>Hosts Overview</h1>
<hr/>

<table class="table">
<% @domains.each do |d| %>
<tr>
 <td colspan="3"><h3><%= d.name %></h3></td>
</tr>
 <% d.hosts.order("name ASC").each do |h| %>
 <tr>
   <td></td>
   <td><%= link_to h.name, h %></td>
   <td>[
    <% h.get_categories.each do |c| %>
    <%= link_to c.name, host_path( h,:anchor => c.name) %> 
    <% end %>
   ]</td>
 </tr>
 <% end %>
<% end %>
</table>

web/app/views/hosts/munin_update.html.erb
#

web/app/views/hosts/show.html.erb
<h1><%= @host.name %></h1>
<div style="float:right">
[
<% @host.get_categories.each do |c| %>
<a href="#<%= c.name %>"><%= c.name %></a> 
<% end %>
]
</div>
<hr/>


<% @host.get_categories.each do |c| %>
<h3><a name="<%= c.name %>"><%= c.name %></a></h3>
<hr/>

<% @host.get_plugins_by_category_id(c.id).each do |p| %>
  <h6>:: <%= p.plg_title %></h6>
  <table>
   <tr>
   	 <!-- day on <%= p.plg_name %> -->
   	 <td><img src="<%= p.graph(Configuration.graph_time_day) %>" /></td>

     <!-- week -->
     <td><img src="<%= p.graph(Configuration.graph_time_week) %>" /></td>
   </tr>
  </table>
<% end %>

<hr/>
<% end %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Carnin Eye</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav">
						<li>
							<%= link_to 'Home', root_url %>
						</li>
						<li class="divider-vertical"></li>
						<li>
							<%= form_tag('/search', :remote => true, :method => "get", :class => "navbar-search pull-left") %>
							<input type="text" name="search_box" id="search_box" class="search-query" placeholder="Search Hosts...">
							</form>
							<ul class="dropdown-menu" id="results" ></ul>
						</li>
						<li class="divider-vertical"></li>
						<li class="dropdown"  id="search_clear">
							<span class="caret"><i class="icon-remove icon-white"></i></span>

						</li>
					</ul>

					<ul class="nav pull-right">
						<li class="divider-vertical"></li>
						<li>
							<%= link_to 'Dashboard', dashboard_url %>
						</li>
					</ul>
				</div>
			</div>
		</div>

		<div style="right:10px;position:absolute;margin-bottom:10px;">
			<small>Update every <%= Configuration.dboard_refresh_time %> seconds <span id="dboard_rf_pause">[<a href="#">pause</a>]</span><span id="dboard_rf_start" style="display:none">[<a href="#">run again</a>]</span></small>
		</div>

		<div class="container">
			<%= yield %>
		</div>

	</body>
</html>

web/app/views/search/_search_from.html.erb
<% @hosts.each do |h|%>
	<li><%= link_to h.name, h %></li>
<% end %>
<% if @hosts.count == 0 %>
	<li>No Host found.</li>
<% end %>

web/app/views/search/query.js.erb
$('#results').html("<%= escape_javascript(render :partial => 'search_from') %>");
$('#results').show();